- name: Install required components
  apt: name=php5-xdebug state=present

- name: Prepare xdebug settings
  template: src=xdebug.ini dest=/tmp/xdebug.ini

- name: Apply xdebug settings
  shell: cat /tmp/xdebug.ini >> /etc/php5/apache2/conf.d/xdebug.ini
  notify: restart apache